language: objective-c

cache:
  - bundler
  - cocoapods
  
before_install:
  - bundle install
  - pod install
  
script: 
  - xcodebuild -workspace CKToolbox.xcworkspace -scheme TableViewDemo -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' test | xcpretty 
  - xcodebuild -workspace CKToolbox.xcworkspace -scheme Tests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' test | xcpretty 
